@startuml Wildlife Simulator - Object Diagram

left to right direction

'=== Objects ===
object "Elephant : Animal" as Elephant
object "Balazs : Ranger" as Balazs
object "V1 : Vehicle" as V1
object ": Poacher" as Poacher1
object "Savanna : Habitat" as Savannah

' === Relationships ===

Savannah *-- Elephant : lives
Savannah -- Balazs : patrols
Savannah -- Poacher1 : incursions

Balazs -- V1 : uses
Balazs -- Elephant : treats

Poacher1 -- Elephant : hunts

@enduml
