/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.LibraryManagementOOP;

public class App {
    public static void main(String[] args) {
        Book book1 = new Book("00001", "Hamsa", "Alisher Navoi", "doston");
        
        System.out.println(book1.isAvailable());
        
    }
}
