@startuml Class Diagram 2
scale 2

skinparam linetype ortho

class Ranger {
    ...
    -stressLevel : int {getter}

    +Ranger(...)
    +getStressLevel() : int
    +increaseStress(int level) : void
    +decreaseStress(int level) : void
    +treatAnimal(Animal animal) : void
    -attemptToTreatAnimal(Animal animal) : boolean
}

note right of Ranger::attemptToTreatAnimal
    attemptToTreatAnimal() {
        return this.efficiency > 5
    }
end note

note left of Ranger::treatAnimal
    treatAnimal(Animal animal) {
        if (!isAvailable) {
            return
        }

        treatmentSuccessful := false

        switch (animal.getState()) {
            case CALM, CURIOUS:
                treatmentSuccessful := attemptToTreatAnimal(animal)
                break

            case DEFENSIVE, AGGRESSIVE:
                if (efficiency > 5) {
                    treatmentSuccessful := attemptToTreatAnimal(animal)
                } else {
                }
                break

            case FLEEING:
                if (efficiency > 7) {
                    treatmentSuccessful := attemptToTreatAnimal(animal)
                }
                break

            case ATTACKING:
                if (efficiency > 8) {
                    treatmentSuccessful := attemptToTreatAnimal(animal)
                }
                break
        }

        if (treatmentSuccessful) {
            animal.stabilize(efficiency, experience)
            stressLevel := max(stressLevel - 2, 0)
            animal.heal(efficiency)
            animal.decreaseStress(efficiency)
        } else {
            stressLevel := min(10, stressLevel + 1)
        }
    }
end note

enum Temprament {
    PASSIVE
    DEFENSIVE
    AGGRESSIVE
    CURIOUS
}

enum State {
    CALM
    ALERTED
    DEFENSIVE
    CURIOUS
    AGGRESSIVE
    FLEEING
    ATTACKING
    STABILIZED
    CRITICAL
}

class Animal {
    -temperament : Temprament {getter, setter}
    -state : State {getter, setter}

    +Animal(...)
    +getTemperament() : Temprament
    +setTemperament(Temprament temperament) : void
}

note left of Animal::getTemperament
    getTemperament() {
        return temperament
    }
end note

note right of Animal::setTemperament
    setTemperament(Temprament temperament) {
        this.temperament := temperament
    }
end note

enum Equipment {
    TRANQUILIZER_KIT
    MEDICAL_KIT
}

class Vehicle {
    ...
    -equipments: Map<Equipment, int> {getter}

    +Vehicle(...)
    +getEquipments() : Map<Equipment, int>
    +hasEquipment(Equipment equipment) : boolean
    +addEquipment(Equipment equipment) : void
    +removeEquipment(Equipment equipment) : void
}

note left of Vehicle::addEquipment
    addEquipment(Equipment equipment) {
        if (equipments.containsKey(equipment)) {
            equipments.put(equipment, equipments.get(equipment) + 1)
        } else {
            equipments.put(equipment, 1)
        }
    }
end note

note right of Vehicle::removeEquipment
    removeEquipment(Equipment equipment) {
        if (equipments.containsKey(equipment)) {
            int count := equipments.get(equipment)
            if (count > 1) {
                equipments.put(equipment, count - 1)
            } else {
                equipments.remove(equipment)
            }
        }
    }
end note

Animal --- Temprament : <<uses>>
Animal --- State : <<uses>>

Vehicle --- Equipment : <<uses>>
Ranger --- Vehicle : <<uses>>
Ranger --- Animal

@enduml